### ISSUE TITLE
Cannot read property raw...

### ISSUE THREAD

**Issue by perpatrik79** [AdyRock/com.onvif#14]
Hi,

Got an onvif-camera that I have included in the app. I seems to include. I am however not able to see the snapshot (i get the error ”cannot read property raw of undefined”). The basic log looks like this:

Log ID: 2020-11-29T12:59:37.864Z
App version 1.1.18

+0:0:0.000: getSystemDateAndTime: Started *****
+0:0:0.142: getSystemDateAndTime: Finished -----
+0:0:1.614: Fetching (44:01:bb:e9:53:9d) NOW image from: http://192.168.1.186/onvif/snapshot
+0:0:0.052: SnapShot error (44:01:bb:e9:53:9d): FetchError: request to http://192.168.1.186/onvif/snapshot failed, reason: socket hang up
    at ClientRequest.<anonymous> (/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:311:20)
    at Socket.socketOnEnd (_http_client.js:460:9)
    at Socket.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
+0:0:0.009: Fetching (44:01:bb:e9:53:9d) NOW image with Basic Auth. From: http://192.168.1.186/onvif/snapshot
+0:0:0.032: SnapShot error (44:01:bb:e9:53:9d): FetchError: request to http://192.168.1.186/onvif/snapshot failed, reason: socket hang up
    at ClientRequest.<anonymous> (/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:311:20)
    at Socket.socketOnEnd (_http_client.js:460:9)
    at Socket.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
+0:0:0.007: Fetching (44:01:bb:e9:53:9d) NOW image with Digest Auth. From: http://192.168.1.186/onvif/snapshot
+0:0:0.031: SnapShot error (44:01:bb:e9:53:9d): FetchError: request to http://192.168.1.186/onvif/snapshot failed, reason: socket hang up
    at ClientRequest.<anonymous> (/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:311:20)
    at Socket.socketOnEnd (_http_client.js:460:9)
    at Socket.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
+0:0:0.003: Fetch NOW error (44:01:bb:e9:53:9d): request to http://192.168.1.186/onvif/snapshot failed, reason: socket hang up
+0:0:8.313: getSystemDateAndTime: Started *****
+0:0:0.307: getSystemDateAndTime: Finished -----

**Comment by AdyRock** [comment]
Hi,

If you open that link in a browser (http://192.168.1.186/onvif/snapshot), do you see the image?

The socket hang basically means the server (in this case the camera) is not responding.

**Comment by perpatrik79** [comment]
The camera is actually located in my holiday-cabin, so I will have to check
it out this weekend.

mån 30 nov. 2020 kl. 16:48 skrev Adrian Rockall <notifications@github.com>:
