### ISSUE TITLE
Socket hang up (connection with homey)

### ISSUE THREAD

**Issue by brzi1973** [AdyRock/com.onvif#23]
What this means? 
Log ID: 2021-12-27T22:02:50.702Z
App version 1.1.32

23:2:50.702: ====  Discovery Starting  ====
23:2:51.094: Reply from {
  "hostname": "192.168.0.23",
  "port": "5000",
  "path": "/onvif/device_service",
  "urn": "urn:uuid:2419d68a-2dd2-21b2-a205-4CB008E326C5",
  "href": "http://192.168.0.23:5000/onvif/device_service"
}
23:2:55.722: ====  Discovery Finished  ====
23:2:55.733: Discovered: [
  {
    "name": "192.168.0.23",
    "data": {
      "id": "4c:b0:08:e3:26:c5"
    },
    "settings": {
      "username": "",
      "password": "",
      "ip": "192.168.0.23",
      "port": "5000",
      "urn": "4c:b0:08:e3:26:c5",
      "channel": -1
    }
  }
]
23:3:14.456: Login-----
23:3:14.467: --------------------------
23:3:14.476: Connect to Camera 192.168.0.23:5000 - 11776132
23:3:14.487: getSystemDateAndTime (192.168.0.23): Started *****
23:3:14.729: Request error (192.168.0.23): socket hang up
Error: socket hang up
    at connResetException (internal/errors.js:604:14)
    at Socket.socketOnEnd (_http_client.js:460:23)
    at Socket.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
23:3:14.967: Request error (192.168.0.23): socket hang up
Error: socket hang up
    at connResetException (internal/errors.js:604:14)
    at Socket.socketOnEnd (_http_client.js:460:23)
    at Socket.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
23:3:14.980: 
data:
undefined
23:3:14.989: getSystemDateAndTime error (192.168.0.23):socket hang up
Error: socket hang up
    at connResetException (internal/errors.js:604:14)
    at Socket.socketOnEnd (_http_client.js:460:23)
    at Socket.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
23:3:14.998: Connection Failed for 192.168.0.23 Port: 5000 Username: 11776132
23:3:15.004: Failed: socket hang up
Error: socket hang up
    at connResetException (internal/errors.js:604:14)
    at Socket.socketOnEnd (_http_client.js:460:23)
    at Socket.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
23:3:26.010: Login-----
23:3:26.011: --------------------------
23:3:26.013: Connect to Camera 192.168.0.23:5000 - 11776132
23:3:26.035: getSystemDateAndTime (192.168.0.23): Started *****
23:3:26.277: Request error (192.168.0.23): socket hang up
Error: socket hang up
    at connResetException (internal/errors.js:604:14)
    at Socket.socketOnEnd (_http_client.js:460:23)
    at Socket.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
23:3:26.518: Request error (192.168.0.23): socket hang up
Error: socket hang up
    at connResetException (internal/errors.js:604:14)
    at Socket.socketOnEnd (_http_client.js:460:23)
    at Socket.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
23:3:26.530: 
data:
undefined
23:3:26.539: getSystemDateAndTime error (192.168.0.23):socket hang up
Error: socket hang up
    at connResetException (internal/errors.js:604:14)
    at Socket.socketOnEnd (_http_client.js:460:23)
    at Socket.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
23:3:26.549: Connection Failed for 192.168.0.23 Port: 5000 Username: 11776132
23:3:26.559: Failed: socket hang up
Error: socket hang up
    at connResetException (internal/errors.js:604:14)
    at Socket.socketOnEnd (_http_client.js:460:23)
    at Socket.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by AdyRock** [comment]
It means the camera is not responding to the request so the connection times out. I have seen this from cameras that are not fully ONVIF compliant and don't support all the base features.
The getSystemDateAndTime is one of the base features that all ONVIF cameras should support as it is required to synchronise the time for secure connections.

**Comment by brzi1973** [comment]
Thank You for reply
